version: "3"
services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/test/datadir:/var/lib/mysql
